[languages.german]
name = "German"
symbol = "de"
layouts = ["qwertz"]

[languages.spanish]
name = "Spanish"
symbol = "es"
layouts = "winkey"

[languages.english]
name = "English"
symbol = "en"
layouts = ["qwerty"]

[languages.persian]
name = "Persian"
symbol = "fa"
layouts = ["winkey", "standard"]

[languages.french]
name = "French"
symbol = "fr"
layouts = ["azerty"]

[languages.russian]
name = "Russian"
symbol = "ru"
layouts = ["standard"]
